inherit_from: .rubocop_todo.yml
AllCops:
  RunRailsCops: true
  Exclude:
    - Guardfile
    - bin/*
    - vendor/bundle/**/*

# Rails default check path
Rails/DefaultScope:
  Include:
    - app/controllers/
    - app/models/
    - app/helpers/
    - app/validators/
    - app/cells/
    - lib/

# Cop supports --auto-correct.
Rails/Output:
  Enabled: false

# Configuration parameters: AlignWith, SupportedStyles.
Lint/DefEndAlignment:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/BarePercentLiterals:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: PreferredDelimiters.
Style/PercentLiteralDelimiters:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/PercentQLiterals:
  Enabled: true

# Cop supports --auto-correct.
Style/SpaceAfterComma:
  Enabled: true

# Cop supports --auto-correct.
Style/TrailingWhitespace:
  Enabled: true

# Cop supports --auto-correct.
Style/UnneededPercentQ:
  Enabled: true
