# MongoDB Configuration
#
# if you want to know about detail configuration,
# see: https://docs.mongodb.org/ecosystem/tutorial/mongoid-installation/#mongoid-configuration
production:
  clients:
    default:
      #database: ss
      #hosts:
      #  - localhost:27017
      uri: mongodb://heroku_2d2hbkpw:bdskmjsi5vldvb80b6sb4bfirl@ds233288.mlab.com:33288/heroku_2d2hbkpw

test:
  clients:
    default:
      database: ss_test
      hosts:
        - localhost:27017
      options:
        truncate_logs: false
        read:
          mode: :primary

development:
  clients:
    default:
      database: ss
      hosts:
        - localhost:27017
      options:
        truncate_logs: false
        #user: username
        #password: password

  # Configure Mongoid specific options. (optional)
  options:
