production: &production
  # Map Api
  #   googlemaps - use googlemaps v3
  #   openlayers - use openlayers3
  #   open_street_map - use OpenStreetMap
  api: googlemaps
  api_key:
  language: ja
  region: jp
  layers:
    - source: "XYZ"
      url: "https://cyberjapandata.gsi.go.jp/xyz/std/{z}/{x}/{y}.png"
      projection: "EPSG:3857"
  open_street_map:
    - source: "OSM"
      url: "https://{a-c}.tile.openstreetmap.org/{z}/{x}/{y}.png"
      projection: "EPSG:3857"

  # Map Addon Center Location
  map_center:
    - 36.204824
    - 138.252924

  # Max Number of Markers in Map Addon
  map_max_point_form: 10

  # Map Addon marker image urls
  map_marker_images:
    googlemaps:
      marker1: "/assets/img/openlayers/marker1.png"
      marker2: "/assets/img/openlayers/marker2.png"
      marker3: "/assets/img/openlayers/marker3.png"
      marker4: "/assets/img/openlayers/marker4.png"
      marker5: "/assets/img/openlayers/marker5.png"
      marker6: "/assets/img/openlayers/marker6.png"
      marker7: "/assets/img/openlayers/marker7.png"
      marker8: "/assets/img/openlayers/marker8.png"
      marker9: "/assets/img/openlayers/marker9.png"
      marker10: "/assets/img/openlayers/marker10.png"
      marker11: "/assets/img/openlayers/marker11.png"
      marker12: "/assets/img/openlayers/marker12.png"
      marker13: "/assets/img/openlayers/marker13.png"
      marker14: "/assets/img/openlayers/marker14.png"
      marker15: "/assets/img/openlayers/marker15.png"
      marker16: "/assets/img/openlayers/marker16.png"
    openlayers:
      marker1: "/assets/img/openlayers/marker1.png"
      marker2: "/assets/img/openlayers/marker2.png"
      marker3: "/assets/img/openlayers/marker3.png"
      marker4: "/assets/img/openlayers/marker4.png"
      marker5: "/assets/img/openlayers/marker5.png"
      marker6: "/assets/img/openlayers/marker6.png"
      marker7: "/assets/img/openlayers/marker7.png"
      marker8: "/assets/img/openlayers/marker8.png"
      marker9: "/assets/img/openlayers/marker9.png"
      marker10: "/assets/img/openlayers/marker10.png"
      marker11: "/assets/img/openlayers/marker11.png"
      marker12: "/assets/img/openlayers/marker12.png"
      marker13: "/assets/img/openlayers/marker13.png"
      marker14: "/assets/img/openlayers/marker14.png"
      marker15: "/assets/img/openlayers/marker15.png"
      marker16: "/assets/img/openlayers/marker16.png"

test:
  <<: *production

development:
  <<: *production
