# translate

production: &production
  api: mock

  mock_api:
    array_size_limit: 100
    text_size_limit: 4000
    contents_size_limit: 4000
    interval: 0.2

  microsoft_translator_text_api:
    key: ""
    url: 'https://api.cognitive.microsofttranslator.com/translate?api-version=3.0'

test:
  <<: *production

development:
  <<: *production
