# translate

production: &production
  mock:
    array_size_limit: 100
    text_size_limit: 4000
    contents_size_limit: 4000
    interval: 0.2
    log_level: info

  microsoft_translator_text:
    key: ""
    url: 'https://api.cognitive.microsofttranslator.com/translate?api-version=3.0'
    array_size_limit: 100
    text_size_limit: 4000
    contents_size_limit: 4000
    interval: 0.2
    log_level: info

test:
  <<: *production

development:
  <<: *production
