require 'spec_helper'

describe Translate::MsTranslator do
  context "test" do

str = <<'EOS'
The Poulnabrone dolmen in Ireland covered at least 22 bodies of the Neolithic period Most of humanity's oldest known archaeological constructions are tombs.[9] Mostly megalithic, the earliest instances date to within a few centuries of each other, yet show a wide diversity of form and purpose. Tombs in the Iberian peninsula have been dated through thermoluminescence to c. 4510 BCE, and some burials at the Carnac stones in Brittany also date back to the fifth millennium BCE.[10] The commemorative value of such burial sites are indicated by the fact that, at some stage, they became elevated, and that the constructs, almost from the earliest, sought to be monumental. This effect was often achieved by encapsulating a single corpse in a basic pit, surrounded by an elaborate ditch and drain. Over-ground commemoration is thought to be tied to the concept of collective memory, and these early tombs were likely intended as a form of ancestor-worship, a development available only to communities that had advanced to the stage of settled livestock and formed social roles and relationships and specialized sectors of activity.[11]
In Neolithic and Bronze Age societies, a great variety of tombs are found, with tumulus mounds, megaliths, and pottery as recurrent elements. In Eurasia, a dolmen is the exposed stone framework for a chamber tomb originally covered by earth to make a mound which no longer exists. Stones may be carved with geometric patterns (petroglyphs), for example cup and ring marks. Group tombs were made, the social context of which is hard to decipher. Urn burials, where bones are buried in a pottery container, either in a more elaborate tomb, or by themselves, are widespread, by no means restricted to the Urnfield culture which is named after them, or even to Eurasia. Menhirs, or "standing stones", seem often to mark graves or serve as memorials,[12] while the later runestones and image stones often are cenotaphs, or memorials apart from the grave itself; these continue into the Christian period. The Senegambian stone circles are a later African form of tomb markers.[13]
Ancient Egypt and Nubia Main article: Art of ancient Egypt An oversized, shallow mask depicting a large face. The face is roughly oval-shaped, but the top of the mask is a horizontal line just above the eyebrows, leaving the entire mask roughly triangular. The entire face is flattened, but the bulbous nose protrudes away from the face. The eyes are large and almond shaped, and both the eyes and braided eyebrows are disproportionally large in comparison with the mouth, which has full lips. The front of the face is clean-shaven, but below the chin, there is a long, narrow, pointed, braided false beard that was characteristic of ancient Egyptian royalty.
Egyptian ceramic coffin mask Egyptian funerary art was inseparably connected to the religious belief that life continued after death – even more, it expressed a belief that "death is a mere phase of life".[14] Aesthetic objects and images connected with this belief were partially intended to preserve material goods, wealth and status for the journey between this life and the next,[15] and to "commemorate the life of the tomb owner ... depict performance of the burial rites, and in general present an environment that would be conducive to the tomb owner's rebirth."[16] In this context are the Egyptian mummies encased in one or more layers of decorated coffin, and the canopic jars preserving internal organs. A special category of Ancient Egyptian funerary texts clarify the purposes of the burial customs. The early mastaba type of tomb had a sealed underground burial chamber but an offering-chamber on the ground level for visits by the living, a pattern repeated in later types of tomb. A Ka statue effigy of the deceased might be walled up in a serdab connected to the offering chamber by vents that allowed the smell of incense to reach the effigy.[17] The walls of important tomb-chambers and offering chambers were heavily decorated with reliefs in stone or sometimes wood, or paintings, depicting religious scenes, portraits of the deceased, and at some periods vivid images of everyday life, depicting the afterlife. The chamber decoration usually centred on a "false door", through which only the soul of the deceased could pass, to receive the offerings left by the living.[18]
Representational art, such as individual portraiture of the deceased, is found extremely early on and continues into the Roman period in the encaustic Faiyum funerary portraits applied to coffins. However, it is still hotly debated whether there was realistic portraiture in Ancient Egypt.[19] The purpose of the life-sized reserve heads found in burial shafts or tombs of nobles of the Fourth dynasty is not well understood; they may have been a discreet method of eliding an edict by Khufu forbidding nobles from creating statues of themselves, or may have protected the deceased's spirit from harm or magically eliminated any evil in it, or perhaps functioned as alternate containers for the spirit if the body should be harmed in any way.[20]
Architectural works such as the massive Great Pyramid and two smaller ones built during the Old Kingdom in the Giza Necropolis and (much later, from about 1500 BCE) the tombs in the Valley of the Kings were built for royalty and the elite. The Theban Necropolis was later an important site for mortuary temples and mastaba tombs. The Kushite kings who conquered Egypt and ruled as pharaohs during the Twenty-fifth dynasty were greatly influenced by Egyptian funerary customs, employing mummification, canopic jars and ushabti funerary figurines. They also built the Nubian pyramids, which in both size and design more closely resemble the smaller Seventeenth dynasty pyramids at Thebes than those of the Old Kingdom near Memphis.[21]
Lower-class citizens used common forms of funerary art—including shabti figurines (to perform any labor that might be required of the dead person in the afterlife), models of the scarab beetle and funerary texts—which they believed would protect them in the afterlife.[22] During the Middle Kingdom, miniature wooden or clay models depicting scenes from everyday life became popular additions to tombs. In an attempt to duplicate the activities of the living in the afterlife, these models show laborers, houses, boats and even military formations which are scale representations of the ideal ancient Egyptian afterlife.[23]
Ancient Greece A carving of a noble robed man and woman apparently leading a demure, robed woman. The man's robe is open, exposing his penis. He holds the hand of the woman.
Relief from a carved funerary lekythos at the National Archaeological Museum of Athens: Hermes conducts the deceased, Myrrhine, to Hades, c. 430–420 BCE
The ancient Greeks did not generally leave elaborate grave goods, except for a coin to pay Charon, the ferryman to Hades, and pottery; however the epitaphios or funeral oration from which the word epitaph comes was regarded as of great importance, and animal sacrifices were made. Those who could afford them erected stone monuments, which was one of the functions of kouros statues in the Archaic period before about 500 BCE. These were not intended as portraits, but during the Hellenistic period, realistic portraiture of the deceased was introduced and family groups were often depicted in bas-relief on monuments, usually surrounded by an architectural frame.[24] The walls of tomb chambers were often painted in fresco, although few examples have survived in as good condition as the Tomb of the Diver from southern Italy or the tombs at Vergina in Macedon. Almost the only surviving painted portraits in the classical Greek tradition are found in Egypt rather than Greece. The Fayum mummy portraits, from the very end of the classical period, were portrait faces, in a Graeco-Roman style, attached to mummies.[25]
Early Greek burials were frequently marked above ground by a large piece of pottery, and remains were also buried in urns. Pottery continued to be used extensively inside tombs and graves throughout the classical period.[26] The great majority of surviving ancient Greek pottery is recovered from tombs; some was apparently items used in life, but much of it was made specifically for placing in tombs, and the balance between the two original purposes is controversial. The larnax is a small coffin or ash-chest, usually of decorated terracotta. The two-handled loutrophoros was primarily associated with weddings, as it was used to carry water for the nuptial bath. However, it was also placed in the tombs of the unmarried, "presumably to make up in some way for what they had missed in life."[27] The one-handled lekythos had many household uses, but outside the household, its principal use was the decoration of tombs.[28] Scenes of a descent to the underworld of Hades were often painted on these, with the dead depicted beside Hermes, Charon or both—though usually only with Charon.[29] Small pottery figurines are often found, though it is hard to decide if these were made especially for placement in tombs; in the case of the Hellenistic Tanagra figurines, this seems probably not the case.[30] But silverware is more often found around the fringes of the Greek world, as in the royal Macedonian tombs of Vergina, or in the neighbouring cultures such as those of Thrace or the Scythians.[31]
The extension of the Greek world after the conquests of Alexander the Great brought peoples with different tomb-making traditions into the Hellenistic sphere, resulting in new formats for art in Greek styles.[32] A generation before Alexander, Mausolus was a Hellenized satrap or semi-independent ruler under the Persian Empire, whose enormous tomb (begun 353 BCE) was wholly exceptional in the Greek world – together with the Pyramids it was the only tomb to be included in the Seven Wonders of the Ancient World. The exact form of the Mausoleum of Halicarnassus, which gave the name to the form, is now unclear, and there are several alternative reconstructions that seek to reconcile the archaeological evidence with descriptions in literature.[33] It had the size and some elements of the design of the Greek temple, but was much more vertical, with a square base and a pyramidal roof. There were quantities of large sculpture, of which most of the few surviving pieces are now in the British Museum.[34] Other local rulers adapted the high-relief temple frieze for very large sarcophagi, starting a tradition which was to exert a great influence on Western art up to 18th-century Neo-Classicism. The late 4th-century Alexander Sarcophagus was in fact made for another Hellenized Eastern ruler, one of a number of important sarcophagi found at Sidon in the modern Lebanon. The two long sides show Alexander's great victory at the Battle of Issus and a lion hunt; such violent scenes were common on ostentatious classical sarcophagi from this period onwards, with a particular revival in Roman art of the 2nd century. More peaceful mythological scenes were popular on smaller sarcophagi, especially of Bacchus.[35]
Etruscans A sculpture of a woman and man reclining together on a couch, their upper bodies to the right and their legs to the left. There is a marked contrast between the high relief busts of their upper bodies and the very flattened lower bodies and legs. They have almond-shaped eyes and long braided hair, and are smiling widely. The man has a beard that is bobbed. The woman's hands are gesticulating in front of her as if she was holding something that is no longer there, or perhaps gesturing while speaking. The man has his right arm draped around the woman's shoulders in an intimate pose, and his right hand on her shoulder also appears to once have held some item. His left hand rests palm up in the crook of the woman's left elbow.
The Etruscan "Sarcophagus of the Spouses", at the National Etruscan Museum in Italy
Objects connected with death, in particular sarcophagi and cinerary urns, form the basis of much of current knowledge of the ancient Etruscan civilization and its art, which once competed with the culture of ancient Rome, but was eventually absorbed into it.[36] The sarcophagi and the lids of the urns often incorporate a reclining image of the deceased. The reclining figures in some Etruscan funerary art are shown using the mano cornuta to protect the grave.[37]
The motif of the funerary art of the 7th and 6th centuries BCE was typically a feasting scene, sometimes with dancers and musicians, or athletic competitions. Household bowls, cups, and pitchers are sometimes found in the graves, along with food such as eggs, pomegranates, honey, grapes and olives for use in the afterlife.[38][39] From the 5th century, the mood changed to more somber and gruesome scenes of parting, where the deceased are shown leaving their loved ones,[40] often surrounded by underworld demons, and psychopomps, such as Charun or the winged female Vanth. The underworld figures are sometimes depicted as gesturing impatiently for a human to be taken away.[41] The handshake was another common motif, as the dead took leave of the living.[41] This often took place in front of or near a closed double doorway, presumably the portal to the underworld. Evidence in some art, however, suggests that the "handshake took place at the other end of the journey, and represents the dead being greeted in the Underworld".[41]
Ancient Rome Main article: Roman funerary art Warrior with cuirass and helmet leaning on his spear in front of a funerary stele; the snake symbolizes the soul of the dead. Marble, Roman artwork from the 1st century BC imitating the Greek classical style of the 5th century BC. From Rhodes.
The burial customs of the ancient Romans were influenced by both of the first significant cultures whose territories they conquered as their state expanded, namely the Greeks of Magna Graecia and the Etruscans.[42] The original Roman custom was cremation, after which the burnt remains were kept in a pot, ash-chest or urn, often in a columbarium; pre-Roman burials around Rome often used hut-urns—little pottery houses.[43] From about the 2nd century CE, inhumation (burial of unburnt remains) in sarcophagi, often elaborately carved, became more fashionable for those who could afford it.[44] Greek-style medallion portrait sculptures on a stela, or small mausoleum for the rich, housing either an urn or sarcophagus, were often placed in a location such as a roadside, where it would be very visible to the living and perpetuate the memory of the dead. Often a couple are shown, signifying a longing for reunion in the afterlife rather than a double burial (see married couple funerary reliefs).[45]
In later periods, life-size sculptures of the deceased reclining as though at a meal or social gathering are found, a common Etruscan style. Family tombs for the grandest late Roman families, like the Tomb of the Scipios, were large mausoleums with facilities for visits by the living, including kitchens and bedrooms. The Castel Sant'Angelo, built for Hadrian, was later converted into a fortress. Compared to the Etruscans, though, there was less emphasis on provision of a lifestyle for the deceased, although paintings of useful objects or pleasant activities, like hunting, are seen.[46] Ancestor portraits, usually in the form of wax masks, were kept in the home, apparently often in little cupboards,[47] although grand patrician families kept theirs on display in the atrium. They were worn in the funeral processions of members of the family by persons wearing appropriate costume for the figure represented, as described by Pliny the Elder and Polybius. Pliny also describes the custom of having a bust-portrait of an ancestor painted on a round bronze shield (clipeus), and having it hung in a temple or other public place. No examples of either type have survived.[48]
By the late Republic there was considerable competition among wealthy Romans for the best locations for tombs, which lined all the approach roads to the city up to the walls, and a variety of exotic and unusual designs sought to catch the attention of the passer-by and so perpetuate the memory of the deceased and increase the prestige of their family. Examples include the Tomb of Eurysaces the Baker, a freedman, the Pyramid of Cestius, and the Mausoleum of Caecilia Metella, all built within a few decades of the start of the Common Era.[49]
In Italy, sarcophagi were mostly intended to be set against the wall of the tomb, and only decorated on three sides, in contrast to the free-standing styles of Greece and the Eastern Empire. The relief scenes of Hellenistic art became even more densely crowded in later Roman sarcophagi, as for example in the 2nd-century Portonaccio sarcophagus, and various styles and forms emerged, such as the columnar type with an "architectural background of columns and niches for its figures".[50] A well-known Early Christian example is the Sarcophagus of Junius Bassus, used for an important new convert who died in 359. Many sarcophagi from leading centres were exported around the Empire.[51] The Romans had already developed the expression of religious and philosophical ideas in narrative scenes from Greek mythology, treated allegorically;[52] they later transferred this habit to Christian ideas, using biblical scenes.[53]
EOS

    item = Translate::MsTranslator.new
    item << str
    item << "good morning"
    item << "september"

    chunks = item.to_translate_chunks
    chunks.each_with_index do |chunk, i|
      puts "chunk#{i} #{chunk.size} #{chunk.content_size}"
    end

    ret = item._translate!("en", "ja")
    p ret
  end
end
